name = "weechat_emoji"
description = "A WeeChat plug-in that displays emoji"
version = "2.0.0"
website = "https://github.com/onox/weechat-emoji"
licenses = "Apache-2.0"
tags = ["emoji", "chat", "irc", "weechat"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAO-Is"]

[[depends-on]]
emojis = "^1.0.1"
weechat_ada = "^3.0.1"

[gpr-set-externals]
EMOJIS_LIBRARY_TYPE = "static-pic"
