name = "weechat_emoji"
description = "A WeeChat plug-in that displays emoji"
version = "2.0.0"
website = "https://github.com/onox/weechat-emoji"
licenses = "Apache-2.0"
tags = ["emoji", "chat", "irc", "weechat"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

configuration.disabled = true

[[depends-on]]
weechat_ada = "^2.0.1"
